---
title       : "Introdução"
subtitle    : "Análise de dados com modelos lineares em R"
author      : "Nicholas A. C. Marino"
job         : "Universidade Federal do Rio de Janeiro"
date        : "github.com/nacmarino/metodosR"
output:
  ioslides_presentation:
    widescreen: true
    smaller: true
---

## Tipos de Modelos    

* Existem dois tipos gerais de modelos que normalmente utilizamos:
    + Modelos lineares: os parâmetros do modelo ($\beta$~0~, $\beta$~1~,..., $\beta$~n~) são lineares, embora as variáveis preditoras (x~1~, x~2~,...,x~n~) possam não ser.  
    + Modelos não-lineares: os parâmetros do modelo ($\beta$~0~, $\beta$~1~,..., $\beta$~n~) não são lineares. Por exemplo: _y_ = $\beta$~0~ * x^$\beta$~1~^.
    
```{r echo = FALSE,message=FALSE,warning=FALSE, fig.align='center', fig.width=5, fig.height=3}
library(ggplot2)
library(gridExtra)

set.seed(58)  
x <- runif(n = 80, min = -3, 3)
y <- x * sin(x)
set.seed(64)
z <- sort(rnorm(n = 80, mean = 10, sd = 3)) * x

grid.arrange(ggplot(data.frame(x,y), aes(x = x, y = y)) + geom_point(colour = "blue") + theme_bw(), ggplot(data.frame(x,z), aes(x = x, y = z)) + geom_point(colour = "red") + theme_bw(), nrow = 1)
```

## Modelos de Regressão em R  

* Existem várias funções disponíveis para rodarmos estes modelos:  
    + Modelos lineares: 
        - `base::lm`, `base::glm`
        - `nlme::lme`, `nlme::gls`
        - `lme4::lmer`, `lme4::glmer`
        - `gam::gam`  
    + Modelos não-lineares: 
        - `stats::nls`, `stats:loess`   
        - `nlme::gnls`  
        - `gnm::gnm`  
        - `gam::gam`  
        
## Modelos de Regressão em R  

* A escolha do modelo e da função dependem da sua pergunta e dos dados que você possui:   
    + Qual a natureza da relação entre sua variável resposta e as variáveis preditoras?  
    + Você possui somente variáveis fixas, ou variáveis aleatórias também?  
    + Você possui medidas repetidas nos mesmos indivíduos ou elas são independentes?  
    + A variância é homogênea?  
    + Que tipo de distribuição segue seus dados?  

## Modelos Lineares em R  

* Serão o nosso foco aqui.    
  
* Rodar um modelo é parte ciência, parte arte:  
    + O modelo segue sua pergunta e/ou desenho experimental;
    + Não existe o modelo certo, mas sim o que se adequa aos seus dados;
    + Você não vai ter apenas um modelo para trabalhar, mas vários modelos possíveis (eu normalmente rodo > 30 modelos para cada variável resposta nos meus trabalhos);
    + Achar o modelo adequado vem primeiro, a significância (estatística) do que está dentro dele vem depois.  
    
## Passo-a-passo (minha fórmula)  

> 1. Saber o que quero fazer;  
> 2. Visualizar os dados e relação entre eles;
> 3. Descobrir o tipo de distribuição da minha variável resposta;
> 4. Estabelecer um modelo nulo;  
> 5. Criar um modelo:  
    + adicionando uma variável de interesse por vez; ou,  
    + com todas as variáveis de interesse de uma vez.  
> 6. Comparar com o modelo nulo;  
> 7. Adicionar/remover variáveis do modelo;  
> 8. Comparar os novo(s) modelo(s);  
> 9. Determinar o modelo mais provável;
> 10. Validar modelo final;
> 11. Testar significância dos termos no modelo;  
> 12. Fazer pós-testes, se necessário.