---
title       : "Regressão"
subtitle    : "Métodos lineares"
author      : "Nicholas dos A. C. Marino"
job         : "Universidade Federal do Rio de Janeiro"
date        : "github.com/nacmarino"
output: 
  ioslides_presentation:
    widescreen: true
#    logo: ./img/rotunda.png 
---

## Conteúdo da Aula

1. Regressão Linear  
2. Regressão Múltipla  
3. Análise de Covariância (ANCOVA)  

---

## Regressão Linear  

1. O que é e qual hipótese testa?
2. Qual é a lógica?
    + Apresentar o modelo e os termos: intercepto, slope e erro
3. Pressupostos da regressão 
4. Como calcular os parâmetros do modelo
5. Teste de significância dos parâmetros do modelo
6. Análise de Variância _vs_ Regressão  

## Regressão Múltipla  

1. O que é?
2. Determinando os parâmetros da regressão múltipla
3. Pressupostos
    + Pressupostos: colineridade
4. Qual a variável mais importante em uma regressão múltipla?  

## Tipo de Soma dos Quadrados

d. Soma dos Quadrados do tipo II _vs_ tipo III
    + https://mcfromnz.wordpress.com/2011/03/02/anova-type-iiiiii-ss-explained/
    + https://www.uvm.edu/~dhowell/StatPages/More_Stuff/Type1-3.pdf

## ANOVA n-way

a. O que é e qual a hipótese nula que está testando?
b. ANOVA two-way _vs_ ANOVA fatorial

## O que é uma interação entre dois fatores?

b. O que é uma interação?

## Soma dos Quadrados em uma two-way ANOVA

c. Como calcular?
    + Between-group é igual
    + Within-group é igual
    + A diferença é a interação
    + Graus de liberdade para a interação

## Análise de Covariância (ANCOVA)

1. O que é?
2. Qual o princípio da ANCOVA?
3. Lógica matemática
4. Pressupostos
